# Generated by Django 5.2.1 on 2025-05-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_recievd',
        ),
        migrations.AddField(
            model_name='order',
            name='is_recieved',
            field=models.BooleanField(default=False),
        ),
    ]
